lifetch/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout_then_login, login
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout_then_login, name='logout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^join/$', views.join, name='join'),
    url(r'^join/success/$', TemplateView.as_view(template_name="accounts/join_success.html"), name='join-success'),
]

lifetch/picture/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^json$', views.json_data, name='json'),
    url(r'^upload$', views.upload, name='upload'),
]

lifetch/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^auth/', include('django.contrib.auth.urls')),
    url(r'^picture/', include('lifetch.picture.urls', namespace='picture'), name='picture'),
    url(r'^accounts/', include('lifetch.accounts.urls', namespace='accounts'), name='accounts'),
    url(r'^admin/', admin.site.urls),
]

lifetch/accounts/models.py
from django.db import models

# Create your models here.

lifetch/picture/models.py
import hashlib

from django.contrib.auth.models import User
from django.core.files.storage import default_storage
from django.db import models, DataError
from django.utils import timezone

from lifetch.picture.exceptions import DuplicateUploadError


class Picture(models.Model):
    owner = models.ForeignKey(User, null=True)
    path = models.ImageField(storage=default_storage)
    name = models.CharField(max_length=128)
    size = models.IntegerField()
    content_type = models.CharField(max_length=128)
    hash = models.CharField(max_length=128)
    date_created = models.DateTimeField(default=timezone.now)

    def save(self, *args, **kwargs):
        if not self.pk:  # file is new
            md5 = hashlib.md5()
            self.name = self.path.name
            self.size = self.path.size
            self.content_type = self.path.file.content_type
            for chunk in self.path.chunks():
                md5.update(chunk)
            self.hash = md5.hexdigest()
            if Picture.objects.filter(hash=self.hash, owner=self.owner).first():
                raise DuplicateUploadError("图片已经存在")
        super(Picture, self).save(*args, **kwargs)

    def to_dict(self):
        return {
            'id': self.id,
            'url': self.path.url,
            'name': self.name,
            'content_type': self.content_type,
            'size': self.size,
            'hash': self.hash
        }

lifetch/accounts/forms.py
import re
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _


class RegistrationForm(forms.Form):

    username = forms.RegexField(regex=r'^\w+$', widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=_("Username"), error_messages={ 'invalid': _("This value must contain only letters, numbers and underscores.") })
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=_("Email address"))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)), label=_("Password"))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)), label=_("Password (again)"))

    def clean_username(self):
        try:
            user = User.objects.get(username__iexact=self.cleaned_data['username'])
        except User.DoesNotExist:
            return self.cleaned_data['username']
        raise forms.ValidationError(_("The username already exists. Please try another one."))

    def clean(self):
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_("The two password fields did not match."))
        return self.cleaned_data

lifetch/picture/forms.py
# -*- coding: utf-8 -*- 
from __future__ import unicode_literals

from django import forms


class UploadFileForm(forms.Form):
    file = forms.ImageField()

lifetch/accounts/views.py
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render, render_to_response

# Create your views here.


# Create your views here.
from django.template import RequestContext

from lifetch.accounts.forms import RegistrationForm


def index(request):
    return render(request, 'accounts/index.html')


def profile(request):
    return render(request, 'accounts/profile.html')


def join(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            User.objects.create_user(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1'],
                email=form.cleaned_data['email']
            )
            return HttpResponseRedirect('/accounts/join/success/')
    else:
        form = RegistrationForm()
    variables = RequestContext(request, {'form': form})
    return render_to_response('accounts/join.html', variables, )

lifetch/picture/views.py
import json

from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import View
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from lifetch.picture.exceptions import DuplicateUploadError
from lifetch.picture.forms import UploadFileForm
from lifetch.picture.models import Picture


@login_required
def index(request):
    return render(request, 'picture/index.html')


@login_required
def json_data(request):
    page = max(int(request.GET.get('page', '1')), 1)
    size = 20
    offset = 20 * (page - 1)
    return HttpResponse(json.dumps(
        [picture.to_dict() for picture in
         Picture.objects.filter(owner=request.user).order_by('-date_created')[offset:offset + size]]
    ), content_type='application/json')


@login_required
@csrf_exempt
def upload(request, **kwargs):
    form = UploadFileForm(request.POST, request.FILES)
    if form.is_valid():
        picture = Picture(path=request.FILES['file'], owner=request.user)
        try:
            picture.save()
            data = {
                'success': True,
                'data': {
                    'id': picture.id,
                    'url': picture.path.url,
                    'name': picture.name,
                    'content_type': picture.content_type,
                    'size': picture.size,
                    'hash': picture.hash
                }
            }
            status = 200
        except DuplicateUploadError as e:
            data = {
                'success': False,
                'message': "图片不能重复上传"
            }
            status = 400

        return HttpResponse(json.dumps(data), content_type='application/json', status=status)
    else:
        return HttpResponse(json.dumps({
            'success': False,
            'message': '请求数据有误'
        }), content_type='application/json', status=400)

lifetch/views.py
# -*- coding: utf-8 -*- 
from __future__ import unicode_literals

from django.shortcuts import render


def home(request):
    return render(request, 'index.html')

lifetch/accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="zh_CN">
<head>
    <title>Lifetch | {% block title %}{% endblock %}</title>
    <link href="//cdn.bootcss.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
    <link href="//cdn.bootcss.com/semantic-ui/2.1.8/semantic.min.css" rel="stylesheet">
</head>
<body>
<div class="ui container">
    <h1>{% block head %}{% endblock %}</h1>
    {% block content %}{% endblock %}
</div>
<script src="//cdn.bootcss.com/jquery/3.0.0-rc1/jquery.min.js"></script>
<script src="//cdn.bootcss.com/semantic-ui/2.1.8/semantic.js"></script>
</body>
</html>

lifetch/accounts/templates/accounts/index.html
{% extends "accounts/base.html" %}
{% block title %}Welcome to Django{% endblock %}
{% block head %}Welcome to Django{% endblock %}
{% block content %}
    <p>Welcome {{ user.username }} !!!</p>
    <a href="/auth/logout/">Logout</a>
{% endblock %}

lifetch/accounts/templates/accounts/join.html
{% extends "accounts/base.html" %}
{% block title %}User Registration{% endblock %}
{% block head %}User Registration{% endblock %}
{% block content %}
    <form method="post" action=".">{% csrf_token %}
        <table border="0">
            {{ form.as_table }}
        </table>
        <input type="submit" value="Register"/>
    </form>
    <a href="/">Login</a>
{% endblock %}

lifetch/accounts/templates/accounts/join_success.html
{% extends "accounts/base.html" %}
{% block title %}注册成功{% endblock %}
{% block head %}
    <div class="ui success message attach">
        <div class="header">
            注册已经完成 <i class="fa fa-check"></i>
        </div>
        <p></p>
    </div>
{% endblock %}
{% block content %}
    感谢您的注册!
    <a href="/">登录</a>
{% endblock %}

lifetch/accounts/templates/accounts/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我的简介</title>
    <link href="//cdn.bootcss.com/normalize/4.1.1/normalize.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'commons.css' %}">
</head>
<body>
{% include '_header.html' %}

<section id="main">

</section>

<footer>

</footer>

</body>
</html>

lifetch/picture/templates/picture/dev/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LiFetch Picture</title>
    <link href="//cdn.bootcss.com/normalize/4.1.1/normalize.min.css" rel="stylesheet"> 
    <link href="//cdn.bootcss.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
    <link href="//cdn.bootcss.com/blueimp-file-upload/9.12.4/css/jquery.fileupload.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'commons.css' %}">
<link href="http://0.0.0.0:8080/static/picture-c98dd.css" rel="stylesheet"></head>
<body>
<header>
    <div id="branding">
        <h1 id="site-name"><a href="/">Lifetch</a></h1>
    </div>
    <div id="apps">
        <a href="{% url 'picture:index' %}" class="{% if active == 'picture' %}active{% endif %}">印象</a>
    </div>
    <div id="user-tools">

        {% if user.is_active %}
            欢迎, <a href="{% url 'accounts:profile' %}"><strong>{{ user.username }}</strong></a> /
            <a href="{% url 'accounts:logout' %}">退出</a>
        {% else %}
            <a href="{% url 'accounts:login' %}?next=/">登录</a>
        {% endif %}

    </div>

</header>


<section id="main">
    <div onsubmit="return false;" id="uploadForm">
        <span class="btn btn-success fileinput-button">
            <i class="glyphicon glyphicon-plus"></i>
            <span>上传文件</span>
            <input id="fileupload" type="file" name="file" multiple data-sequential-uploads="true"
                   data-form-data='{"csrfmiddlewaretoken": "zle7fWyDWCxU6vzHNJ5unEpsPNW9CwNV"}'>
        </span>
        <div id="uploadBox">
            <div class="title">上传状态 <span class="global-status"></span></div>
        </div>
    </div>
    <div id="board">

    </div>
    <div id="expand"></div>
</section>

<footer>

</footer>

<script>
    var LFT = window.LFT = {};
    LFT.csrf_token = '{{ csrf_token }}';
</script>
<script src="//cdn.bootcss.com/jquery/2.2.4/jquery.min.js"></script>
<script src="//cdn.bootcss.com/blueimp-file-upload/9.12.4/js/vendor/jquery.ui.widget.min.js"></script>
<script src="//cdn.bootcss.com/blueimp-file-upload/9.12.4/js/jquery.fileupload.min.js"></script>
<script type="text/javascript" src="http://0.0.0.0:8080/static/picture-9dc71.js"></script></body>
</html>

lifetch/picture/templates/picture/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LiFetch Picture</title>
    <link href="//cdn.bootcss.com/normalize/4.1.1/normalize.min.css" rel="stylesheet">
    <link href="//cdn.bootcss.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
    <link href="//cdn.bootcss.com/blueimp-file-upload/9.12.4/css/jquery.fileupload.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'commons.css' %}">
    <link rel="stylesheet" href="{% static 'picture/css/index.css' %}">
</head>
<body>
{% include '_header.html' with active='picture' %}

<section id="main">
    <div onsubmit="return false;" id="uploadForm">
        <span class="btn btn-success fileinput-button">
            <i class="glyphicon glyphicon-plus"></i>
            <span>上传文件</span>
            <input id="fileupload" type="file" name="file" multiple data-sequential-uploads="true"
                   data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
        </span>
        <div id="uploadBox">
            <div class="title">上传状态 <span class="global-status"></span></div>
        </div>
    </div>
    <div id="board">

    </div>
</section>

<footer>

</footer>
<script>
    var LFT = window.LFT = {};
    LFT.csrf_token = '{{ csrf_token }}';

</script>
<script src="//cdn.bootcss.com/jquery/2.2.4/jquery.min.js"></script>
<script src="//cdn.bootcss.com/blueimp-file-upload/9.12.4/js/vendor/jquery.ui.widget.min.js"></script>
<script src="//cdn.bootcss.com/blueimp-file-upload/9.12.4/js/jquery.fileupload.min.js"></script>
<script src="//cdn.bootcss.com/lodash.js/4.13.0/lodash.min.js"></script>
<script src="//cdn.bootcss.com/backbone.js/1.3.3/backbone-min.js"></script>
<script src="{% static 'picture/js/index.js' %}"></script>
</body>
</html>

lifetch/templates/_header.html
<header>
    <div id="branding">
        <h1 id="site-name"><a href="/">Lifetch</a></h1>
    </div>
    <div id="apps">
        <a href="{% url 'picture:index' %}" class="{% if active == 'picture' %}active{% endif %}">印象</a>
    </div>
    <div id="user-tools">

        {% if user.is_active %}
            欢迎, <a href="{% url 'accounts:profile' %}"><strong>{{ user.username }}</strong></a> /
            <a href="{% url 'accounts:logout' %}">退出</a>
        {% else %}
            <a href="{% url 'accounts:login' %}?next=/">登录</a>
        {% endif %}

    </div>

</header>

lifetch/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LiFetch Picture</title>
    <link href="//cdn.bootcss.com/normalize/4.1.1/normalize.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'commons.css' %}">
</head>
<body>

{% include '_header.html' %}

<section id="main">

</section>

<footer>

</footer>
</body>
</html>